# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\"\n\x0fSessionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2t\n\x0eSessionManager\x12\x31\n\x0cStartSession\x12\x0f.SessionRequest\x1a\x10.SessionResponse\x12/\n\nEndSession\x12\x0f.SessionRequest\x1a\x10.SessionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONREQUEST']._serialized_start=17
  _globals['_SESSIONREQUEST']._serialized_end=53
  _globals['_SESSIONRESPONSE']._serialized_start=55
  _globals['_SESSIONRESPONSE']._serialized_end=89
  _globals['_SESSIONMANAGER']._serialized_start=91
  _globals['_SESSIONMANAGER']._serialized_end=207
# @@protoc_insertion_point(module_scope)
